version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- pwsh: nuget restore
build:
  project: MyMessenger.sln
  verbosity: minimal
artifacts:
- path: '\'
  name: MyMessenger_All_Files