version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- pwsh: scripts\version.ps1
before_build:
- pwsh: nuget restore
build_script:
- pwsh: dotnet build /p:Version="$env:assembly_version"
artifacts:
- path: '\'
  name: MyMessenger_All_Files